### ISSUE TITLE
Sentence Transformer for ALBERT

### ISSUE THREAD

**Issue by MaheshChandrra** [UKPLab/sentence-transformers#105]
Hi Team UKP Lab,

I'm looking for ALBERT model to use it with sentence transformer for creating embedding's of dimension 128,I've tried running the script which was provided in the examples for creating the model for ALBERT,due to some technical issues,I'm unable to create it,can you please provide the same just like you've provided for other models at:   https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/

I tried this as well but I'm getting embedding's of dimension 768 but not 128,tried replacing word_embedding_model.get_word_embedding_dimension() to 128,but didn't work,please help.

```
from sentence_transformers import models, SentenceTransformer

word_embedding_model=models.ALBERT('albert-base-v2')


pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)


```

**Comment by nreimers** [comment]
Hi @MaheshChandrra 
I achieved rather poor performances with ALBERT, hence, not providing pretrained models (in order to keep things simple). Is there a specific reason you like to use ALBERT in contrast to the other models?

To change the dimension, you must add a dense layer after the pooling:
```
word_embedding_model=models.ALBERT('albert-base-v2')

pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
pooling_mode_mean_tokens=True,
pooling_mode_cls_token=False,
pooling_mode_max_tokens=False)

dense_model = models.Dense(in_features=768, out_features=128)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model, dense_model])
```

The dense model reduces your 768 dimensions to 128

**Comment by MaheshChandrra** [comment]
Thanks @nreimers  for the quick response, due to Memory issues,embedding's are occupying thrice the memory than the document itself,so thinking of moving to ALBERT to see if it works any good with less dimension,can you please suggest any other model where in the dimension  size is less and performance is high.
any help would be appreciated.

Thanks in advance.

**Comment by nreimers** [comment]
Hi @MaheshChandrra 
You can apply the dense layer to any of the models to reduce the embedding size.

Otherwise I personally like the basic approaches like average word embeddings / Deep Averaging Networks / or LSTM networks. They still achieve quite good performances and are a lot less complex than BERT & Co.

These models are also implemented in this framework so for example, for a DAN network, see:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training_stsbenchmark_avg_word_embeddings.py

**Comment by MaheshChandrra** [comment]
Sure,will try , Thanks again @nreimers  !!
