### ISSUE TITLE
Normalization of embeddings

### ISSUE THREAD

**Issue by sbhttchryy** [UKPLab/sentence-transformers#1084]
Hello, are the embeddings generated from using any model normalized? If not, is there a process to normalize them? Thank you for your response.

**Comment by nreimers** [comment]
For most models the embeddings are not normalized. You can set `normalize_embeddings=True` when calling the encode method to get normalized embeddings.

**Comment by sbhttchryy** [comment]
Thank you for your fast response. I have one question. Have you conducted experiments using the normalized embeddings? In case yes, have you noticed any improvements or decrease in performance, if any?

**Comment by nreimers** [comment]
Depends how you use them.

When you use them with cosine similarity, there is no difference. Because cosine similarity normalizes the embeddings, so you will get identical results. 

If you use them with e.g. k-means clustering, then normalizing them is better: k-means uses euclidean distance. However, with normalized embeddings, eucl. distance is proportional to cosine similarity. And results are better when you use cossim than eucl. distance.
