### ISSUE TITLE
When run application, max_seq_len should be set.

### ISSUE THREAD

**Issue by guotong1988** [UKPLab/sentence-transformers#11]
![image](https://user-images.githubusercontent.com/4702353/63233624-db66a980-c263-11e9-8969-1a934ac1524d.png)

If we train the model with 512 max_seq_len, but encode a sentence with 513 tokens, then error.

**Comment by nreimers** [comment]
This is a difference to pytorch transformers. Max seq len of n allows actually n real tokens. But as the CLS and SEP tokens are added, BERT receives an input sequence length of n+2 tokens.

You can fix it by setting the max seq len to 510 for BERT, which would be equivalent to 512 with pytorch transformers. 

-Nils Reimers

**Comment by guotong1988** [comment]
No, 
If we train the model with 512 max_seq_len, but encode a sentence with 700 tokens, then error.

**Comment by nreimers** [comment]
Which version do you use? In the v0.1.0 there was bug, that max_seq_len was not respected at inference time. I.e., in that version, you must ensure that your sentences are not too long.

This bug was fixed in v0.2.0.

Note: The maximal value for max_seq_len for BERT is 510 in this implementation (max_seq_len=510 is equal to a sequence length of 512 for pytorch transformers).

**Comment by guotong1988** [comment]
I use the old one.
