### ISSUE TITLE
Using Sentence Transformers with AWS SageMaker

### ISSUE THREAD

**Issue by sagar1025** [UKPLab/sentence-transformers#1107]
Has anyone used this Sentence Transformers with AWS SageMaker? I'm curious to know how I would go about this.
My objective is to perform a semantic search in real time. My dataset is about 250K rows (and growing)

SageMaker seems like a viable option since I can create, store, update models and most importantly, it's easier to create an endpoint to which my application can use.

**Comment by sagar1025** [comment]
I found a nice blog here. For anyone else who might want to use SageMaker with sentence transformers:

https://aws.amazon.com/blogs/machine-learning/building-an-nlu-powered-search-application-with-amazon-sagemaker-and-the-amazon-es-knn-feature/

**Comment by vng510** [comment]
@sagar1025 have you implemented this?  I'm looking into this also.  It looks like the general idea is that that sagemaker endpoint returns the embedding and another product is needed to do the similarity search.  I wonder if it's feasible to have the endpoint load the dataset and maintain the state like it does for the model (I'm guessing that the model state is maintained as long as the endpoint is up).

**Comment by sagar1025** [comment]
@vng510  I'm almost done with the development of this. Next step for me is to do a load/stress test to figure out how many instances would be required for the production environment. 

You're on the right track. First you generate the embeddings for each product. Next, create an ElasticSearch (ES) index. Then push all product info (along with the embeddings for each product) to ES.

The lambda function is the only service exposed. When the lambda function is invoked, the first api call it makes is to sagemaker. The sagemaker endpoint returns an embedding based on the string passed. It does this by calling the "predict" method in the model . This embedding is then passed to a 2nd api call to elastic search. Elastic search performs a KNN based search and returns the top N nearest neighbors for that embedding.

As to your question about whether it's feasible to store a model, I think it should be. The whole purpose of using Sagemaker is so that you can create, tune, and update ML models and use them for inference. In the blog post, you will be required to "save" and "deploy" the model. If a model is deployed successfully, it will be available for inference. Another way to reduce the time taken for search/generate embeddings is to [reduce the dimensions](https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/distillation/dimensionality_reduction.py).


The notebook associated with the above blog post can be found here
https://github.com/aws-samples/amazon-sagemaker-nlu-search/blob/master/nlu-based-item-search.ipynb

This is the repository that contains all the code
https://github.com/aws-samples/amazon-sagemaker-nlu-search

**ES no longer supports AWS Managed ES** (See https://github.com/elastic/elasticsearch-py/issues/1687 and https://github.com/elastic/elasticsearch-py/issues/1666)

If you still decide to use ES, here are some issues I ran into. Maybe you wont run into all of these, maybe you will:

1. Authentication for ES. You will need to map your [IAM roles in the Kibana console](https://forums.aws.amazon.com/thread.jspa?threadID=320322). Only then will you be able to use IAM roles to access ES.
2. I would to not recommend you to make the ES domain inside a VPC. It makes authenticating every request a nightmare.
3. Use Access policies using IP address and roles to limit who can access your public ES domain.
4. The [Elastic Search Python Client](https://elasticsearch-py.readthedocs.io) is not very helpful. Stick to `requests` module instead. The Elastic Search Python Client does not recognize AWS Elastic search domains for some reason.

**Comment by vng510** [comment]
@sagar1025, thanks for the detail write-up.  I also reached out to AWS and they suggested for a data size of around 400k entries (this is my data size), Elasticsearch is may be an overkill.  Instead, they suggest two options possible alternatives.  I copied their exact response below.  I will let you know once I am done with the actual implementation.

1.
As you suggest, you can have the endpoint load the embeddings into memory, using the entrypoint, and, when you invoke the endpoint, it both creates the new embedding and searches for the closest previous embedding. I don’t see a problem with this. Since there are only 400K embeddings, this should be fine. Keep in mind though that endpoints have a timeout of 1 minute (which can be increased to 2 minutes by request), so this solution will not be ideal if these two steps together are more than one minute. 

2.
Related to this, you might want to consider decoupling the process of creating the embedding from comparing to previous embeddings. You could do this, for example, by having a Lambda function invoke the endpoint, get the embedding, and compare the results to previous embeddings (Lambda has a timeout of 15 minutes).  You could also use a SageMaker Inference Pipeline for this.

**Comment by moshonkel** [comment]
Is there any way (comparable to the huggingface .deploy() way ) to just set up a sagemaker api endpoint with a sentence transformer (prefereably this one: https://huggingface.co/Sahajtomar/German-semantic)?

**Comment by sagar1025** [comment]
I don't think there is a straight forward way to do it. Take a look at "SageMaker Model Hosting" section here:

https://github.com/aws-samples/amazon-sagemaker-nlu-search/blob/master/nlu-based-item-search.ipynb

**Comment by NikolaMorena** [comment]
Here's a snippet (SageMaker Python notebook) that deploys SageMaker endpont with a sentence transformer, all-mpnet-base-v2 in this case:

`from sagemaker.huggingface import HuggingFaceModel
import sagemaker 

role = sagemaker.get_execution_role()

# Hub Model configuration. https://huggingface.co/models
hub = {
  'HF_MODEL_ID':'sentence-transformers/all-mpnet-base-v2', # model_id from hf.co/models
  'HF_TASK':'feature-extraction' # NLP task you want to use for predictions
}

# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
   env=hub,
   role=role, # iam role with permissions to create an Endpoint
   transformers_version="4.6", # transformers version used
   pytorch_version="1.7", # pytorch version used
   py_version="py36", # python version of the DLC
)

# deploy model to SageMaker Inference
predictor = huggingface_model.deploy(
   initial_instance_count=1,
   instance_type="ml.m5.large",
   endpoint_name="nikola-test"
)

data = {
    "inputs": ["This is an example sentence", "Each sentence is converted"]
}

# request
embeddings=predictor.predict(data)
print(embeddings)`

**Comment by Yuanyuan-Shen** [comment]
Hi @NikolaMorena, this script works well. Thank you. Just one issue, the generated embeddings output has 7 vectors with each of 384 length. Removing one sentence from the input, and there are still 7 vectors. I'm wondering where does the number 7 come from?

**Comment by NikolaMorena** [comment]
Hi @Yuanyuan-Shen ,
A transformer model outputs a vector for each token. In your case, 7 is the length of the tokenizer output, including some special tokens.  According to [the documentation](https://huggingface.co/sentence-transformers/msmarco-distilbert-base-tas-b),  the input sentence/paragraph embeddings is the final hidden state of special aggregate sequence representation token ([CLS]) that is embedded as the first token of every sequence. So, in order to get sentence/paragraph embeddings, you have to post-process ML model output by applying “cls pooling” operation on-top of the contextualized word embeddings produced by ML model. Sounds complicated, but in reality it's simple:

def cls_pooling(model_output):
    return [sublist[0] for sublist in model_output]

The output of cls_pooling function is a matrix [inputsCount, 384] - actually one s-embeddings vector of size 384 for each input.

**Comment by spencerjsmall** [comment]
> Hi @Yuanyuan-Shen ,
> 
> A transformer model outputs a vector for each token. In your case, 7 is the length of the tokenizer output, including some special tokens.  According to [the documentation](https://huggingface.co/sentence-transformers/msmarco-distilbert-base-tas-b),  the input sentence/paragraph embeddings is the final hidden state of special aggregate sequence representation token ([CLS]) that is embedded as the first token of every sequence. So, in order to get sentence/paragraph embeddings, you have to post-process ML model output by applying “cls pooling” operation on-top of the contextualized word embeddings produced by ML model. Sounds complicated, but in reality it's simple:
> 
> 
> 
> def cls_pooling(model_output):
> 
>     return [sublist[0] for sublist in model_output]
> 
> 
> 
> The output of cls_pooling function is a matrix [inputsCount, 384] - actually one s-embeddings vector of size 384 for each input.

This saved my life thank you. Couldn't figure out why the embeddings shape was different from it normally is using sentence-transformers directly.
