### ISSUE TITLE
How to combine title, description and genre information

### ISSUE THREAD

**Issue by krlng** [UKPLab/sentence-transformers#1117]
This is more a question than an issue (I hope thats okay Nils):

I want to encode documents that all have a title, a short description and some genre information. Currently I just concat those, but surely the information when the title ends and a description starts would help the Model. I tried to add "\n" between those text fragments, but the tokeniser is just dropping that. What would be a good way to provide the transformer the structural information, whether a word belonged to the title or the description text?å

**Comment by nreimers** [comment]
Hi @krlng 
I would add new special tokens to your model & tokenizer (you can find some examples here in the issues or in the transformers issues how to add new special tokens to a huggingface transformer model).

And then have you text look like this:
text = your_genre+" [TITLE] "+ your_title +" [DESCRIPTION] "+your_description

With the two special new tokens [TITLE] and [DESCRIPTION]

And then train with your data on this format

As the model will truncate at the end, I would sort the fields so that the shortest field is first (which is your genre?) and the longest last (which is your description?)

**Comment by krlng** [comment]
Thanks Nils, this does work technically, but does not give me much improvement. I only trained the sentence encoder, but did not run training on the Basemodel (GBERT). Would that be required as well?

**Comment by nreimers** [comment]
Usually training the base model is node required. But not that not all base models perform equally well for deriving embeddings. So it is always worthwhile to test some few different models.

**Comment by krlng** [comment]
Thanks
