### ISSUE TITLE
Get sentence vectors directly from bert base model

### ISSUE THREAD

**Issue by dheerajiiitv** [UKPLab/sentence-transformers#121]
Hi,

I want to get sentence embedding vectors from Bert pre-trained word embeddings without training on any data? How can I do it ?

**Comment by nreimers** [comment]
Hi @dheerajiiitv 
Like this:
````
# Use BERT for mapping tokens to embeddings
word_embedding_model = models.BERT('bert-model-name-OR-path')

# Apply mean pooling to get one fixed sized sentence vector
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
```

Best
Nils Reimers

**Comment by dheerajiiitv** [comment]
Thanks for the quick reply,

Hi @nreimers, I just wanted to know when I trained the model, what things it changes to get so much better result. 
I am using it for a scenario where I want to find rich sentence embeddings but I don't have any training data so how can I use it. Currently, I am using USE to get sentence embeddings.

One more query - Suppose I trained a model now I want to get word embeddings from the trained model that is the output from the first pooling layer, how can I do it in Sentence bert package.


Thanks in advance

**Comment by dheerajiiitv** [comment]
Hi @nreimers ,

I found a way to do it (last query) - Just trained a model using sent-transformer than convert the model to the TensorFlow model that uses bert-as-service to calculate embeddings.

**Comment by nreimers** [comment]
Hi @dheerajiiitv 

> One more query - Suppose I trained a model now I want to get word embeddings from the trained model that is the output from the first pooling layer, how can I do it in Sentence bert package.
This is already on my agenda for the next version. It would be a quite easy addition to SentenceTransformer.py. Just update the encode function so that it does not return 'setnence_embedding' but 'word_embeddings.

> I am using it for a scenario where I want to find rich sentence embeddings but I don't have any training data so how can I use it. 
You could of course use one of the pre-trained models , that was trained on e.g. NLI oder STS data.

But in general you would need some data that expresses the desired similarity. Often you can construct this from the data itself (see the Wikipedia sections dataset):
There, two sentences appearing in the same paragraph are treated as similar, and sentences in different paragraphs are treated as dissimilar. You can then train on this information.

> I just wanted to know when I trained the model, what things it changes to get so much better result.
When training, the complete BERT model is fine-tuned. Then, a mean pooling is applied on the last layer to get a fixed-sized word embedding.

Best
Nils Reimers

**Comment by dheerajiiitv** [comment]
Thanks for the answer!!!!!
