### ISSUE TITLE
setting evaluation_steps parameter in fit() doesn't work

### ISSUE THREAD

**Issue by peacej** [UKPLab/sentence-transformers#127]
It seems changing `training_steps` to `global_step` in these 2 lines would fix the problem?
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L383-L384

Thanks for this awesome library BTW~

**Comment by nreimers** [comment]
Ho @peacej 
The parameter evaluation_steps determines after how many steps in each epoch the model should be evaluated on the dev set. Setting it to 1000 will run the evaluation after 1k steps in an epoch.

If you epoch has less than 1k steps, then the evaluation will only performed after the epoch.

I made it depended on the training_steps so that you have a clear behavior in each epoch. Otherwise it may run in epoch 1 the evaluation after 1k steps, in epoch 2 after 300 steps (in that epoch) etc.

Best
Nils Reimers

**Comment by peacej** [comment]
Thanks @nreimers! I was confused and thought that a "step" was a single example in the data but now I realize one step is actually one batch.
