### ISSUE TITLE
encode() method unexpectedly sensitive to input length?

### ISSUE THREAD

**Issue by mattiaciollaro** [UKPLab/sentence-transformers#1356]
This seems counterintuitive to me:

```python
import numpy as np
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-mpnet-base-v2")

sentences = ["hello", "goodbye", "you say I say"]

np.array_equiv(model.encode(sentences)[0], model.encode(sentences[0]))
# False

np.array_equiv(model.encode(sentences)[1], model.encode(sentences[1]))
# False
```

However, note that the arrays are equivalent if e.g. `sentences = ["hello", "goodbye"]`, i.e. if the input sentences have the same length (1 word).

```python
np.array_equiv(model.encode(sentences[:2])[0], model.encode(sentences[:2][0]))
# True

np.array_equiv(model.encode(sentences[:2])[1], model.encode(sentences[:2][1]))
# True
```

This makes me thing that [this sorting operation](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L147-L149) may be responsible for what seems to be a slightly counterintuitive/unexpected behavior of the `SentenceTransformer.encode` method.

Granted, the difference/dissimilarity between the embeddings is negligible in practice. Still, this is somewhat unexpected behavior in my view.

Any thoughts?

**Comment by nreimers** [comment]
Yes, this is known, cannot be fixed, and is no issue at all.

When encoding multiple texts, all texts are padded to the length of the longest text. These padding tokens slightly change the resulting text embedding.

So encode(sentences[0]) encodes the text without padding, while encode(sentences) encodes the first sentence with padding.

But this is usually no issue, as the resulting vector is really really close in both cases. Hence, instead of checking for equivalence, you should check if their distance is smaller than a specific value.

Further on this topic:
Computations on GPUs are non-deterministic, so it can happen that you run the exact same code with the exact same inputs and still get slightly different results each time from the GPU. Hence, you should not expect equivalence, but always check if the difference is smaller than a specific threshold.

**Comment by mattiaciollaro** [comment]
Thank you for the prompt response!

> When encoding multiple texts, all texts are padded to the length of the longest text. These padding tokens slightly change the resulting text embedding.

Makes sense.

> Computations on GPUs are non-deterministic, so it can happen that you run the exact same code with the exact same inputs and still get slightly different results each time from the GPU. Hence, you should not expect equivalence, but always check if the difference is smaller than a specific threshold.

Thanks for the heads up on this as well.

Thanks for a great package! Closing this "issue".
