### ISSUE TITLE
Unsupervised Fine-tuning

### ISSUE THREAD

**Issue by maiskovich** [UKPLab/sentence-transformers#178]
Hello,

I have been checking the original BERT paper and I am wondering if with this library I can fine tune or continue training a pre trained model with unlabeled data. I saw the concept of removing random words from the sentence and train the model to predict those and also the idea of  “next sentence prediction” task, can I implement this with a custom dataset that doesn't have labels? or otherwise, can you please explain how the dataset should look like for training?

Sorry if I am not fully understanding this concepts and this is something that is already happening.

Thank you

**Comment by nreimers** [comment]
Hi @maiskovich 
For fine-tuning the language model you should have a look at the hugginface transformer repo:
https://github.com/huggingface/transformers

This repository fine-tunes the models, so that it can be used for unsupervised tasks like clustering. However, for the fine-tuning here, you need some notion  (label) of similarity between a sentence pair.

**Comment by maiskovich** [comment]
Thank you
