### ISSUE TITLE
Memory leak in SentenceTransformer instantiation

### ISSUE THREAD

**Issue by qrdlgit** [UKPLab/sentence-transformers#2298]
```
for i in range(5):
    model = SentenceTransformer("thenlper/gte-large")
    del model
    gc.collect()
```
Not a huge issue, but does make doing certain things awkward.

**Comment by chschroeder** [comment]
This is reguarly observed, but no progress has been made over several months. See #1793 for more details.

**Comment by tomaarsen** [comment]
I'm struggling to reproduce this using this snippet in particular. I would like to invest some time to track down this issue, but have not had any luck. If any of you happen to have a snippet showing this behaviour, then I'd love to have a look at it.

- Tom Aarsen

**Comment by qrdlgit** [comment]
My guess is the issue is somewhere in the huggingface stuff.  Workaround has been to push them to external procs.

**Comment by tomaarsen** [comment]
Thanks for the heads up, I'll try to look into the multi process issue. A naive question: did you use `stop_multi_process_pool` to stop the started processes?

- Tom Aarsen

**Comment by chschroeder** [comment]
@qrdlgit This might be accurate, I remember that in one of those topic we identified a model that was problematic. In case the issue is in the HF parts, I would suspect the issues to be in the model-specific code. I have been running a lot of experiments where I compare plain BERT/DistilRoBERTa/RoBERTa (HF transformers implementations) against SetFit trained sentence-transformer models. All models have the same size, but only the sentence-transformer models occasionally fail.

@tomaarsen A while ago I tried to find any memory "leaks", with limited time admittedly, but was unsuccessful. It might not necessarily be a leak but also just unfavorable timing of the garbage collector, where a garbage collection can also lead to GPU memory being freed. The methods in sentence-transformers are quite complex (in the sense of "too big") at times. For example, if a variable of a torch tensor could go out of scope sooner, it can be garbage collected sooner, and the GPU memory can be freed.

**Comment by tomaarsen** [comment]
When I find some time, I may use env variables to limit my VRAM and try and train some models until I reach OOMs. Perhaps I can narrow things down that way.

- Tom Aarsen

**Comment by qrdlgit** [comment]
> Thanks for the heads up, I'll try to look into the multi process issue. A naive question: did you use `stop_multi_process_pool` to stop the started processes?
> 
> * Tom Aarsen

I used ctrl-c :)  it was an external process executed by os.system.  But yeah, I could add a try/except there

Agreed, it could be mostly GC caused, but something HF is doing is aggravating whatever the GC does poorly.

**Comment by DogitoErgoSum** [comment]
Any news on this?

**Comment by manickavela29** [comment]
Any update on this issue?
