### ISSUE TITLE
How to convert  embedding vector to text ？

### ISSUE THREAD

**Issue by chengzhen123** [UKPLab/sentence-transformers#2300]
I use  the script below to convert  text  to embeddings 
```
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(text)
```

But how to convert  embeddings to text ？

**Comment by jobergum** [comment]
There is no straightforward way to do this. But, with data (text to embedding), you can learn a lossy inverse function (embedding to text) as described in https://openreview.net/forum?id=wK7wUdiM5g0

**Comment by tomaarsen** [comment]
Hello!

As mentioned above, this should not really be attempted.

- Tom Aarsen

**Comment by Badal-2** [comment]
My Opinion on this. as far as I read About  vector into text. This is Totally impossible to convert  vector into text. Because we can't find or convert Exact text by Vector.  from DB.

 Embedding means converting text into a vector.
🔴 This is more complex and depends on the type of vector. 

 But we have another way we can use of  Retrieve but Here is also not 100% chance will come Exact Text From Vector. What we want.

TEXT ---> VECTOR---> SAVE(DB)----> COMPARE ---> NEAREST TEXT RETURN
