### ISSUE TITLE
util.paraphrase_mining returning scores only above 0.98

### ISSUE THREAD

**Issue by sinangokce** [UKPLab/sentence-transformers#2392]
Hey,
I'm using util.paraphrase_mining (sentence-transformers v2.2.2) to get similarity scores (cosine) in a corpus of ~20k texts with the encoder model being all-MiniLM-L6-v2 and with the parameters query_chunk_size=500, corpus_chunk_size=1000, top_k=500000, max_pairs=5000000. 
The returned list of triplets contain scores only above 0.98. I was wondering why the lower scores don't appear. 
Thanks in advance for your answer!

**Comment by tomaarsen** [comment]
Hello!

`paraphrase_mining` returns a maximum number of text pairs, in your case 5 million. However, in total there are 20k * 20k = 400 million text pairs. As a result, returning "only" the top 5 million pairs means that you only return the top 1.25% of all pairs. That's why the returned triplets all have high similarity scores: they're simply the top triplets.

- Tom Aarsen
