### ISSUE TITLE
Loading Local Model

### ISSUE THREAD

**Issue by MehmetTheBard** [UKPLab/sentence-transformers#2425]
Hello everyone, 
I want to try SentenceTransformers but have to load models on secured environment with no internet connection. I tried to download model files from HuggingFace and run the code below

`passage_encoder = SentenceTransformer('./dpr-ctx_encoder-multiset-base')`

it returns that error what should I do?

`No sentence-transformers model found with name ./dpr-ctx_encoder-multiset-base. Creating a new one with MEAN pooling.`

**Comment by tomaarsen** [comment]
Hello!

This is a warning rather than an error: it indicates that the model that you are loading is not a [Sentence Transformers model](https://huggingface.co/models?library=sentence-transformers), but a regular [Transformers model](https://huggingface.co/models?library=transformers).
This is not an issue per se, as Sentence Transformers can load a lot of regular Transformers models. However, the Transformers models generally output an embedding per *token*, while Sentence Transformers wants embeddings per *sentence*. So, it adds a "Mean pooling" layer to get the mean of all token embeddings to produce a sentence embedding. That's the warning that you see.

Instead, the recommendation is to use the DPR models that are converted to Sentence Transformers: https://huggingface.co/sentence-transformers/facebook-dpr-ctx_encoder-single-nq-base
This one is automatically compatible with Sentence Transformers. My recommendation is to move this model to the secured environment in the same way that you've done for `dpr-ctx_encoder-multiset-base`, and you can update your code to `passage_encoder = SentenceTransformer('./facebook-dpr-ctx_encoder-multiset-base')`. (Assuming that you moved the model to the `facebook-dpr-ctx_encoder-multiset-base` folder).

Hope this helps!

- Tom Aarsen

**Comment by MehmetTheBard** [comment]
That helped a lot! Thanks.
