### ISSUE TITLE
Is it possible to do "minimal" installation of this library? Just, Just for inference?

### ISSUE THREAD

**Issue by AayushSameerShah** [UKPLab/sentence-transformers#2444]
### 🤔 Background 
When I am installing `pip install sentence-transformers` it downloads as expected but the download stack is so huge. Obviously it has to be, but it it goes for downloading:
- torch
- torchvision
- _other dependencies..._

This easily goes over `1GB` (in Linux). And I also **don't want to use CUDA**, so no need their dependencies as well.

### 🙋🏻‍♂️ Question
Is it possible to perform the minimal installation?

My usecase is to only use the following model with the following code:
```python
# The model loading
sentence_transformers_model = SentenceTransformer("all-MiniLM-L6-v2")

# Corpus loading and getting top k

query_embedding = sentence_transformers_model.encode(query, convert_to_tensor=False)

hits = util.semantic_search(query_embedding, embeddings, top_k=k)
hits = hits[0]  # Get the hits for the first query
top_k = []
for hit in hits:
    if hit["score"] > 0.40:
        top_k.append(corpus[hit["corpus_id"]])
```

> - Nothing much of work. So, just for this use-case do I have to download a lot of dependencies? 
> - What should I do to perform this minimal installation?

Thanks.

**Comment by tomaarsen** [comment]
Hello!

Great question! On Linux, the default torch installation will indeed pull a CUDA-compiled wheel. However, CPU-compiled wheels also exist. If you install `sentence-transformers` directly, it will immediately start installing its dependencies, `torch` included, and you'll end up with the CUDA-compiled one.

Instead, we want to start off by installing `torch` with CPU specifically:
```
pip install torch --index-url https://download.pytorch.org/whl/cpu
```
And then when we install `sentence-transformers`, it'll recognize that we already have `torch` and it won't install the CUDA-compiled one. 

Secondarily, the current most recent version on PyPI has `torchvision` as a dependency. However, the upcoming release has removed this dependency. My recommendation would be to install the `master` version of this repository rather than the PyPI one, as then you won't have to install `torchvision`.

This should do it:
```
pip install git+https://github.com/UKPLab/sentence-transformers.git
```

That should be the minimal set of dependencies that you can get away with, I believe.

- Tom Aarsen

**Comment by AayushSameerShah** [comment]
@tomaarsen 
You. Are. Amazing.
Thank you very very much for your clean and easy-to-follow response. 
This helps a lot.

Thanks again ✌🏻
