### ISSUE TITLE
Reopening discussion on multi-GPU training?

### ISSUE THREAD

**Issue by AlexJonesNLP** [UKPLab/sentence-transformers#2489]
Hi, I know that multi-GPU training has been brought up here multiple times before, but to my understanding it has not yet been implemented in the library. Are there plans to incorporate this functionality in the near future? Or is it already possible, in which case I would appreciate some pointers on how to do it.

Thanks!

EDIT: I just noticed this PR: [#1215](https://github.com/UKPLab/sentence-transformers/pull/1215). Closing this discussion but will reopen if I have questions.

**Comment by tomaarsen** [comment]
Hello!

We indeed have a few issues open regarding Multi-GPU support (and even a PR or two), and I'd like to confirm that I am indeed working on it. To be specific, I am intending for the Training Refactor in #2449 to include Multi-GPU support (it doesn't yet). In this PR, I have started updating the training code to rely on a subclass of the `transformers` Trainer, which is Multi-GPU compatible. I still need to arrange access to a multi-gpu machine myself so that I can implement & test its support.

I am well aware that not having this support is inhibiting powerusers from training the models that they'd like to.

- Tom Aarsen
