### ISSUE TITLE
AttributeError: 'SentenceTransformerTrainingArguments' object has no attribute 'dataloader_persistent_workers'

### ISSUE THREAD

**Issue by Davit98** [UKPLab/sentence-transformers#2741]
The code below (based on https://www.sbert.net/docs/sentence_transformer/training_overview.html#trainer)

```
...

trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    loss=loss,
    evaluator=dev_evaluator,
)
trainer.train()
```

results in the error shown in the picture below

<img width="1424" alt="Screen Shot 2024-06-10 at 13 38 27" src="https://github.com/UKPLab/sentence-transformers/assets/21690840/abac75fa-0c10-44c3-bcdb-2c0ff707f23d">

I am confused that in the [v3.0 documentation](https://www.sbert.net/docs/package_reference/sentence_transformer/training_args.html#sentence_transformers.training_args.SentenceTransformerTrainingArguments) the attribute `dataloader_persistent_workers` is included in the available argument list of `SentenceTransformerTrainingArguments` class, however, when I look at the source code, `SentenceTransformerTrainingArguments` indeed does not have `dataloader_persistent_workers` attribute. Furthermore, the code uses `self.args.dataloader_prefetch_factor` which as I understand will lead to another error even if the previous error is fixed because `SentenceTransformerTrainingArguments` does not possess an attribute named `dataloader_prefetch_factor` either. 

Am I doing something wrong?

**Comment by cmashkin** [comment]
Check transformers module version. E.g. try `transformers==4.41.2`

**Comment by tomaarsen** [comment]
Hello!

Apologies for the delay, I was on vacation last week.
@cmashkin is right on the money - the problem here is that your `transformers` version is too old. I've created #2757 to ensure that people who install `sentence-transformers` will use `transformers` 4.38.0 or newer, as that is the version that introduced the `dataloader_prefetch_factor` that you also ran into.
Until then, you can just run:
```
pip install -U transformers
```
and everything should work again.

- Tom Aarsen
