### ISSUE TITLE
Cannot restart training of model that necessitates `trust_remote_code=True` flag

### ISSUE THREAD

**Issue by patricebechard** [UKPLab/sentence-transformers#2917]
## What is the issue

If your training is interrupted and you want to restart it with flag `resume_from_checkpoint`, the `Trainer` tries to reload the model via the `_load_from_checkpoint` method. However, this method does not take as input any keyword arguments. In the case where you are finetuning a model that necessitates the flag `trust_remote_code=True`, we are currently unable to reload the model to restart training.

https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/trainer.py#L734-L738

**Comment by tomaarsen** [comment]
Hello!

Thanks for sharing, this issue makes a lot of sense. I tried to avoid most of these issues by updating the state dict of the original model rather than overriding the model with a fresh one, but `trust_remote_code` indeed remains an issue. I think the only solution is to store whether the model was loaded with `trust_remote_code` internally, and to reuse that from the original model.
I'll make a PR to set that up.

- Tom Aarsen
