### ISSUE TITLE
Support for Quantization Aware Training

### ISSUE THREAD

**Issue by lejinvarghese** [UKPLab/sentence-transformers#3031]
Is it possible to perform `Quantization Aware Training` on Sentence Transformers, beyond [fp16 and bf16](https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L404-L408) that are directly supported in the transformer training_args? Are there other options for doing binary quantization during training, other than using the Intel/Neural Compressor [INCTrainer](https://huggingface.co/docs/optimum/main/intel/neural_compressor/optimization#quantization) or OpenVino [OVTrainer](https://huggingface.co/docs/optimum/main/intel/neural_compressor/optimization#quantization)?

**Comment by tomaarsen** [comment]
Hello!

I'm afraid the INCTrainer/OVTrainer/ORTTrainer aren't directly compatible with Sentence Transformers. Beyond that, you can load models in specific quantization with `bitsandbytes` via `model_kwargs`, and you can use PEFT as well (though that doesn't do quantization per se).

I do want to preface that there's a difference between quantization from [Speeding up Inference](https://sbert.net/docs/sentence_transformer/usage/efficiency.html) and [Embedding Quantization](https://sbert.net/examples/applications/embedding-quantization/README.html). The former allows for faster inference, and the latter is a post-processing of the output embeddings so that downstream tasks (e.g. retrieval) are faster. 

So there's a difference between:
* Quantization-aware training, i.e. training such that the model has minimal performance loss when quantizing the model weights for faster inference.
* Quantization-aware training, i.e. training such that the model has minimal performance loss when quantizing the output embeddings for faster downstream tasks.

For the first one, there's not great options out of the box to my knowledge, and for the latter you can consider the Binary Passage Retrieval Loss ([bpr_loss](https://github.com/beir-cellar/beir/blob/main/beir/losses/bpr_loss.py)) which is compatible with Sentence Transformers.

- Tom Aarsen

**Comment by lejinvarghese** [comment]
@tomaarsen thank you for the detailed reply 🙇, the recommendations make sense, will try out the bpr_loss.
