### ISSUE TITLE
UnboundLocalError: local variable 'SentenceTransformer' referenced before assignment

### ISSUE THREAD

**Issue by riyajatar37003** [UKPLab/sentence-transformers#3086]
UnboundLocalError: local variable 'SentenceTransformer' referenced before assignment

tried pip install with upgrade but same error

**Comment by tomaarsen** [comment]
I suspect one of a few things is happening:
1. You've forgotten to import `SentenceTransformer`
2. You've made a folder called `sentence_transformers` which messes up the `from sentence_transformers import SentenceTransformer`
3. You've turned `SentenceTransformer` into a variable with something like `SentenceTransformer = 12`

I suspect the issue is on your end. An interesting solution is to go to https://huggingface.co/chat/ and ask it "I'm getting the `UnboundLocalError: local variable 'SentenceTransformer' referenced before assignment` error with the following code, could you tell me 1) why and 2) how I should fix it?

<paste the code here>"

And then I suspect it will be able to tell you.

- Tom Aarsen

**Comment by riyajatar37003** [comment]
Thanks.
My bad it was import error.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
