### ISSUE TITLE
How to load ModernBERT model correctly?

### ISSUE THREAD

**Issue by Hannibal046** [UKPLab/sentence-transformers#3141]
Hi Teams,

I want to ask how to properly load [ModernBERT](https://huggingface.co/blog/modernbert) using SentenceTransformer?

The main difficulty I met is about the weight loading of prediction head as defined [here](https://github.com/huggingface/transformers/blob/f42084e6411c39b74309af4a7d6ed640c01a4c9e/src/transformers/models/modernbert/modeling_modernbert.py#L1121-L1123) where `ModernBertPredictionHead` is not included in the `AutoModelClass`. I tried to use the following code:
```python
import torch
from sentence_transformers import SentenceTransformer,models
model_name_or_path = "answerdotai/ModernBERT-base"
modules = []
modules.append(models.Transformer(model_name_or_path))

## head
modules.append(models.Dense(768,768,activation_function=torch.nn.GELU()))
modules.append(models.Dense(768,768,activation_function=torch.nn.Identity()))

## pooling
modules.append(models.Pooling(768,pooling_mode="mean"))

## classifier
modules.append(models.Dense(768,1))

model = SentenceTransformer(modules=modules,device="cpu")
```

However, it seems that `Dense` before `Pooling` is not supported and would throw an error:
```
KeyError: 'sentence_embedding'
```

**Comment by tomaarsen** [comment]
Hello!

Sentence Transformers fully ignores the pooling heads of all `transformers` models. For ModernBert, but also for Bert, Roberta, etc. 
Instead, Sentence Transformers places their own pooling on top. 

With other words, it's not a problem that you can't use the pooling solution from `transformers` when loading the `AutoModel`. 

So it should just be as simple as:
```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("answerdotai/ModernBERT-base")
# and now you can train!
```

That's how I used it for https://huggingface.co/tomaarsen/ModernBERT-base-gooaq.

- Tom Aarsen

**Comment by Hannibal046** [comment]
Hi, 

Thanks for the prompt response!

By using `model = SentenceTransformer("answerdotai/ModernBERT-base")` to load the model, the weight of `ModernBertPredictionHead` is not loaded. However, If I use `AutoModelForSequenceClassification`, the only newly initialized weight would be `classifier`. Do I understand this correctly? Is is possible to load the pretrained `ModernBertPredictionHead` weight  with SentenceTransformer?

**Comment by tomaarsen** [comment]
Indeed, the `ModernBertPredictionHead` is not loaded. This is rather normal for Sentence Transformer models. For example, for BERT models the [pooler](https://github.com/huggingface/transformers/blob/ef1f54a0a7c3c21eff90cb94d4b58d5b67f79b3e/src/transformers/models/bert/modeling_bert.py#L979) is also ignored/excluded, idem with [RoBERTa](https://github.com/huggingface/transformers/blob/ef1f54a0a7c3c21eff90cb94d4b58d5b67f79b3e/src/transformers/models/roberta/modeling_roberta.py#L813).

If you use `AutoModelForSequenceClassification`, the classifier weights are indeed newly initialized, because the 2 original ModernBERT models aren't trained for sequence classification - they need to be finetuned still.

The normal way to turn the ModernBERT models into a Sentence Transformer model is simply
```
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("answerdotai/ModernBERT-base") # perhaps specify `attn_implementation` or `reference_compile`
# and now you can train!
```

However, you can use custom modules in Sentence Transformers if you'd really like to add that last dense + activation + norm - each module is just a `nn.Module` subclass, so you can make your own. I don't think it's necessary, however.

---

> Additionally, I'm looking to fine-tune this model by adding a classifier (Linear) layer. Would you have any recommendations for this use case?

Do you mean finetuning the model to become a classifier? Then I would look into the finetuning scripts with `transformers` for Sequence/Text Classification. Sentence Transformers is usually used if your desired outputs are embeddings rather than classes (although it's still very viable for classifiers, see [SetFit](https://github.com/huggingface/setfit/) - they often just require already being finetuned for embeddings first)

- Tom Aarsen
