### ISSUE TITLE
Question: Why train from scratch?

### ISSUE THREAD

**Issue by aclifton314** [UKPLab/sentence-transformers#47]
First, thank you very much for your work on sentence-transformers. I can't wait to start using it and really digging into it to understand everything. 

I have a very naive question. Why would someone want to train a model from scratch? I can see fine-tuning a pre-trained model on a dataset that is, say, more representative of the vocabulary for your task. But what would be the various reasons for wanting to train, say, bert-base-uncased from scratch?

**Comment by nreimers** [comment]
See #36, especially this link:
https://github.com/google-research/bert/issues/651#issuecomment-503557477

The BERT models in this repository are fine-tuned, so that they produce well working sentence embeddings for unsupervised tasks like clustering, semantic search or STS.

As outline in the link post, training BERT from scratch on custom data can be done, but training is expensive and there is usually not a crazy performance boost. So I think in most cases fine-tuning is the better option.

Best regards
Nils Reimers

**Comment by aclifton314** [comment]
@nreimers 
Thanks!
