### ISSUE TITLE
training SBERT for clustering on low resource language

### ISSUE THREAD

**Issue by stellaywu** [UKPLab/sentence-transformers#570]
Thank you for the very useful repo! 

I'm trying to use this library to do clustering with a handful of labels (less than 1000 not so clean labels) on a low resource language. Although SBERT seems to have improved embeddings, the clustering is not performing well. Would love to get some feedback on the approach. 

I have pertained BERT for the low resource language and have done the following :

1. Used labels and BERT checkpoint and TripletLoss to train SBERT (the evaluation function shows improvement of accuracy from 0.67 to 0.90!) 
2. Used SBERT to encode available unlabelled sentences (about 150k ) and clustering on the resulting encoded sentence. Tried the fast clustering and KMeans +UMAP and HDBSCAN + UMAP, fast clustering seems to give poor results, KMeans discovered some meaningful clusters but many mixed, HDBSCAN found a blob and a few small clusters. 

My questions is how to get better clusters? Is my labels a limiting factor to the SBERT embedding quality 

Thanks!!

**Comment by nreimers** [comment]
Hi @stellaywu 
It is had to answer, as I don't know your data.

When you use TripletLoss, you have to be careful how your negative looks like. If your negatives are always chosen with a certain strategy, the model specializes to learn this strategy. However, it fails to get the overall picture.

Better loss functions are BatchAllTripletLoss:
https://www.sbert.net/docs/package_reference/losses.html#batchalltripletloss

And MultipleNegativesRankingLoss
https://www.sbert.net/docs/package_reference/losses.html#multiplenegativesrankingloss 

Because here we use all examples in a batch as negative examples. This forces the model to learn the overall picture of your vector space. And the overall picture is quite important for clustering.

I.e., with triplet loss, a large blob is often no issue because you just do two comparisons. The above mentioned losses force the model to avoid to create a large blob.

**Comment by stellaywu** [comment]
thanks @nreimers for the quick reply! Changed loss to BatchAllTripletLoss, HDBSCAN still produce a blob, I suspect my data has some outliers that just overshadow the blob. fast clustering seems producing promising results. 
However fast clustering seems to require lots of memory for the `topk` function, it crushes for >20k data points. 
is that expected behavior?

**Comment by nreimers** [comment]
Hi @stellaywu 

The function computes the pairwise cosine similarity. So with 20k data points, it computes a matrix 20k x 20k = 400 Mio. Elements = about 2 GB in size.

The larger the number of elements, the larger the matrix (grows quadratic with the number of elements). But this makes it quite fast.

If memory is an issue, the function code must be changed and be chunked into smaller part, i.e., compute the cosine matrix only for chunks of e.g. 10k x 10k and aggregate the results of topk. This decrease the run-time, i.e., you have the classical memory vs. run-time trade off.

**Comment by stellaywu** [comment]
thanks @nreimers that makes a lot of sense! will close the issue now.
