### ISSUE TITLE
MNLI test set results

### ISSUE THREAD

**Issue by yukioichida** [UKPLab/sentence-transformers#65]
Hi,

First, nice work and thanks for sharing the code.

Did you guys check the performance of your model during NLI finetuning model on MNLI or SNLI dev/test sets? If yes, can you share the accuracy results?

**Comment by nreimers** [comment]
Hi @yukioichida 
Thanks :)

I did not check the performance on the NLI datasets while tuning. Currently, the evaluator for accurarcy has some bugs that will be fixed in version 2.0.4, which I plan to release soon. Then, it will be easy to monitor the performance on the NLI dev sets.

Best
Nils Reimers
