### ISSUE TITLE
Distillation of 'distilroberta-base-msmarco-v2' for QA task

### ISSUE THREAD

**Issue by AmitChaulwar** [UKPLab/sentence-transformers#694]
I am looking for a way to distill the `distilroberta-base-msmarco-v2` model so that I can use a small multilingual model for QA task. I tried to distill that model with `make_multilingual.py`  script and parallel sentence datasets such as tedtalks. My assumption behind that was that, if we map the embeddings of parallel sentences, the questions and answers of MSMarco datasets will be automatically mapped. However, I get better performance (e.g. higher NDCG) value by training from scratch instead of this distillation procedure. Is there something wrong in my procedure?

**Comment by nreimers** [comment]
Hi @AmitChaulwar 
On which dataset did you compute NDCG and to what do you compare?

Note: In make_multilingual.py, only individual sentences are used. However, that model must also encode complete paragraphs that consists of multiple sentences. So I think the issue is there: It only learn parallel sentences, but then must work well on a paragraph level.

One solution to this could be to use parallel paragraphs. But sadly there are not some many parallel paragraph datasets available. But from the TED 2020 dataset, you could also create a paragraph version by e.g. combining several sentences together.
