### ISSUE TITLE
model.encode() output is on 'cpu' even if the model is on 'cuda'

### ISSUE THREAD

**Issue by abhishek0318** [UKPLab/sentence-transformers#819]
By default `convert_to_numpy=True`. This causes the embedding to move to 'cpu' even if ithe model is on 'cuda'. If 'convert_to_tensor=True` the embedding shouldn't be moved to 'cpu`.

Code now is,
```
if convert_to_numpy:
    embeddings = embeddings.cpu() 
```
This issue could be fixed by another condition,
```
if convert_to_numpy and not convert_to_tensor:
    embeddings = embeddings.cpu() 
```

**Comment by nreimers** [comment]
Hi @abhishek0318 
Thanks for pointing this out.

This is already fixed in the master branch:
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L167

If convert_to_tensor is True, it will disable convert_to_numpy.

It will be part of the next release (v1.0.0), which will be released this week.
