### ISSUE TITLE
Recall calculation in InformationRetrievalEvaluator is incorrect

### ISSUE THREAD

**Issue by lambdaofgod** [UKPLab/sentence-transformers#964]
There is a bug in [this line](https://github.com/UKPLab/sentence-transformers/blob/46a149433fe9af0851f7fa6f9bf37b5ffa2c891c/sentence_transformers/evaluation/InformationRetrievalEvaluator.py#L223), `num_correct` should be divided by `min(len(query_relevant_docs), k_val`.

What it computes now makes no sense, as it underestimates recall - for example if k=1 and first result is correct, it doesn't output 1 as it should, but 1/`query_relevant_docs`, so the "recall" is significantly lower than it should be.

**Comment by nreimers** [comment]
Hi @lambdaofgod 
The line is correct, and I agree with you that it does not make much sense.

Recall@k is defined at hits_retrieved / total_relevant_hits. If k=1, you retrieve 1 relevant hit, and there are 100 relevant hits overall in your complete set, then Recall@1 is still 1/100.


We discussed the issue here:
https://arxiv.org/pdf/2104.08663.pdf

In Appendix E. What you propose is Capped Recall@k. I agree that capped Recall@k makes more sense, but it still rather uncommon. Most papers use the Recall@k as defined above.

**Comment by lambdaofgod** [comment]
Ok, so wouldn't you say that adding this metric makes sense?
I can do that.
Let me know what you think and the potential problems that it could create.

**Comment by nreimers** [comment]
E.g. when we use https://github.com/cvangysel/pytrec_eval , the official evaluation script for TREC from NIST, we get from the following code:
```python
import pytrec_eval
import json

qrel = {
    'q1': {
        'd1': 1,
        'd2': 1,
        'd3': 1,
    },
}

run = {
    'q1': {
        'd1': 3.0,
        'd2': 2.0,
        'd3': 1.0,
    },
    
}

evaluator = pytrec_eval.RelevanceEvaluator(
    qrel, {'recall_1'})

print(json.dumps(evaluator.evaluate(run), indent=1))
```

A recall of 0.333   for Recall@1 for our system (it retrieves 1 relevant hit with 3 relevant hits in total).


Yes, I think adding a capped recall@k could make sense.
