### ISSUE TITLE
How can I feed a dataframe to bert?

### ISSUE THREAD

**Issue by boscoj2008** [UKPLab/sentence-transformers#977]
(1) I would like to know if there is a way I can feed a dataframe to sentence bert..
(2) I don't have labeled data,  how can I fine-tune bert for a product matching task?

**Comment by nreimers** [comment]
1) Best way is to convert your text column to a list of sentences / strings. Then pass it to the encode function.

2) Unsupervised learning is difficult and in 98% of the cases it is better to use one of the pre-trained models. Otherwise, you can find here an overview:
https://www.sbert.net/examples/unsupervised_learning/README.html

But note, that these methods are only better in few cases than using one of the provided models like paraphrase-mpnet-base-v2.
